project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd

  
website:
  title: ""
  search: false

  navbar:
    title: MGMT 767 
    search: false
    right:
      - text: Code Binder
        href: https://mybinder.org/v2/gh/bbcx-investments/mgmt767-binder.git/HEAD
      - text: Slide Decks
        file: slides.qmd

format: 
  html:
    theme: cosmo
    scss: styles.css
      



