project:
  type: website
  output-dir: docs
  render:
    - index.qmd

  
website:
  title: ""
  search: false

  navbar:
    title: MGMT 767
    search: false
    right:

      - text: Code Binder
        href: https://mybinder.org/v2/gh/bbcx-investments/mgmt767-binder.git/HEAD


format: 
  html:
    theme: cosmo
    scss: styles.css
      



